name: mimo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  audioplayers: ^5.2.0
  change_app_package_name: ^1.1.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  glowy_borders: ^1.0.2
  path: ^1.8.3
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  android: true
  ios: true
  web:
    generate: true
    background_color: "#1B1B1F"
  windows:
    generate: true
    icon_size: 256 # min:48, max:256, default: 48
  macos:
    generate: true

flutter:
  uses-material-design: true

  assets:
    - assets/audio/correct.wav
    - assets/audio/wrong.wav

  fonts:
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-Bold.ttf
