name: mimo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  glowy_borders: ^1.0.2
  path: ^1.8.3
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Josef
      fonts:
        - asset: assets/fonts/JosefinSans-Bold.ttf
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Regular.ttf
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-Bold.ttf
